Repository jijun0129/ecocapture, pull requests merged in 2024-12, with the labels that each got.

#12 fix: 버튼 클릭 가능하도록 수정
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/ecocapture/TextActivity.kt
Labels: Fix

#13 fix: 이미지 검색 결과 창에서 뒤로가기 버튼 작동하도록 수정
  app/src/main/java/com/example/ecocapture/TextResultActivity.kt
Labels: Fix

#15 feat: 데이터 베이스 추가 및 텍스트 검색 기록 추가
  app/src/main/java/com/example/ecocapture/SqliteData.kt
  app/src/main/java/com/example/ecocapture/Tab2Fragment.kt
  app/src/main/java/com/example/ecocapture/TextActivity.kt
  app/src/main/res/layout/fragment_tab2.xml
  app/src/main/res/layout/item_result.xml
Labels: Feat

#17 feat: 로그 액티비티 추가하여 상세보기 지원
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ecocapture/LogDetailActivity.kt
  app/src/main/java/com/example/ecocapture/Tab2Fragment.kt
  app/src/main/res/layout/activity_log_detail.xml
Labels: Feat

#19 fix: 검색기록 페이지로 이동시 업데이트 하도록 수정
  app/src/main/java/com/example/ecocapture/Tab2Fragment.kt
Labels: Fix

#20 Kiyeon/design2
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ecocapture/ImageResultActivity.kt
  app/src/main/java/com/example/ecocapture/LogDetailActivity.kt
  app/src/main/java/com/example/ecocapture/MenuActivity.kt
  app/src/main/java/com/example/ecocapture/TextActivity.kt
  app/src/main/res/drawable/btn_default.xml
  app/src/main/res/layout/activity_image.xml
  app/src/main/res/layout/activity_image_result.xml
  app/src/main/res/layout/activity_log_detail.xml
  app/src/main/res/layout/activity_text.xml
  app/src/main/res/layout/item_result.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: Style

#21 검색기록 페이지 수정 완료
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/ecocapture/SqliteData.kt
  app/src/main/java/com/example/ecocapture/TextActivity.kt
Labels: Feat, Fix
